---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

library(data.table)
library(ggplot2)
library(readrba)
library(lubridate)
library(ggrepel)

rounder <- function(value, round) {
  sign <- sign(value)
  mag <- abs(value)
  out <- ceiling(mag / round) * round * sign
  
  return(out)
}

# Custom breaks so they appear in increments of the cash rate
cust_breaks <- function(vec) {
  seq(rounder(range(vec)[1], 0.25), rounder(range(vec)[2], 0.25) + 0.25, 0.25) - 0.15
}

```

# ASX Implied Cash Rate

This repo automatically scrapes the ASX 30 Day Interbank Cash Rate Futures Implied Yield Curve from [here](https://www.asx.com.au/markets/trade-our-derivatives-market/derivatives-market-prices/short-term-derivatives) and converts it into a simple csv.

## Implied yield curve

```{r load-data, include=FALSE}
all_data <- fread("combined-data/all_data.csv", colClasses = c("Date", "numeric", "Date"))

ocr_ts <- setDT(read_rba_seriesid("FIRMMCRTD"))
ocr <- ocr_ts[date == max(date), value]

```

```{r graph-main, echo=FALSE, dev='svg', warning=FALSE}

graph_data <- all_data[date >= floor_date(Sys.Date(), "month")]

past_seq <- seq.Date(max(graph_data$scrape_date) - 7*8, max(graph_data$scrape_date) - 1, by = "1 week")

ggplot() +
  geom_hline(yintercept = ocr, colour = "black", linewidth = 0.5, linetype = "solid") +
  geom_line(aes(x = date, y = cash_rate, colour = factor(scrape_date)), linewidth = 1, data = graph_data[scrape_date %in% past_seq]) +
  geom_line(aes(x = date, y = cash_rate), colour = "black", linewidth = 1.2, data = graph_data[scrape_date == max(scrape_date)]) +
  labs(
    title = "Implied cash rate over past 8 weeks",
    subtitle = paste0(format(max(graph_data$scrape_date), "%d %b %Y"), " in bolded black, solid line = current OCR"),
    x = NULL, y = NULL, colour = "Date") +
  scale_x_date(date_labels = "%b", date_breaks = "1 months", date_minor_breaks = "1 month") +
  scale_y_continuous(breaks = function(vec) cust_breaks(vec), sec.axis = dup_axis()) +
  scale_colour_viridis_d(labels = function(x) format(as.Date(x), "%d %b"), guide = guide_legend(reverse = TRUE)) +
  theme_bw()

```

```{r graph-change, echo=FALSE, dev='svg', warning=FALSE}
# Graph the change in the implied cash rate between the past 2 days, past week and past 4 weeks

change_data <- all_data[date >= floor_date(Sys.Date(), "month")]
change_data <- change_data[scrape_date %in% c(max(scrape_date), max(scrape_date) - 1, max(scrape_date) - 7, max(scrape_date) - 28)]

change_data <- dcast(change_data, date ~ scrape_date, value.var = "cash_rate")

if (length(names(change_data)) == 5) {
  setnames(change_data, new = c("date", "4 weeks ago", "1 week ago", "1 day ago", "today"))
  
  col_class <- sapply(change_data, class)
  cols <- names(col_class)[col_class == "numeric"]
  change_data[, (cols) := lapply(.SD, function(x) today - x), .SDcols = cols]
  change_data[, today := NULL]
  change_data <- melt(change_data, id.vars = "date")
  change_data[, variable := ordered(variable, c("1 day ago", "1 week ago", "4 weeks ago"))]
  
  ggplot(change_data, aes(x = date, y = value * 100, fill = variable)) +
    geom_hline(yintercept = 0, colour = "black", linewidth = 0.5, linetype = "solid") +
    geom_col(position = "dodge") +
    labs(title = "Change in implied cash rate (bps)",
         x = NULL, y = NULL, fill = "Relative to:") +
    scale_x_date(date_labels = "%b %Y", date_breaks = "3 months", date_minor_breaks = "1 month") +
    scale_y_continuous(sec.axis = dup_axis()) +
    theme_bw()

}
```

```{r graph-next-cut, echo=FALSE, dev='svg', warning=FALSE}
graph_data <- copy(all_data)

# Data prior to Feb 23 is a bit funky because it was still peak hiking cycle
graph_data <- graph_data[scrape_date > "2023-02-01"]

# Only future values should exist
graph_data <- graph_data[date >= as.Date(scrape_date) %m-% months(1)]

# Join actual cash rate data
graph_data[ocr_ts, on = .(scrape_date >= date), actual_ocr := value]

# Calculate the months when cash rate cuts become fully priced in
graph_data[, cr_gap := cash_rate - actual_ocr]
graph_data[, cr_incr := cr_gap %/% 0.25]

# Keep cutting cycles only
graph_data <- graph_data[cr_incr < 0]

# Keep predictions that are in the future only
graph_data <- graph_data[date >= floor_date(Sys.Date(), "month")]

# Remove duplicates so each scrape date and cr_incr has only the earliest date value
setorder(graph_data, scrape_date, date)
graph_data <- unique(graph_data, by = c("scrape_date", "cr_incr"))

# Using a CJ with all the combinations of scrape_date, date and cr_incr, create a new data.table that has NA for all the missing dates
graph_data2 <- CJ(scrape_date = unique(graph_data$scrape_date),
                  cr_incr = unique(graph_data$cr_incr))
graph_data2[graph_data, on = .(scrape_date, cr_incr), date := date]

# Keep the latest date and go back in 1 week increments only
dates_to_keep <- data.table(scrape_date = unique(graph_data2$scrape_date))
setorder(dates_to_keep, -scrape_date)
dates_to_keep[, days_before := max(scrape_date) - scrape_date]
dates_to_keep[, weeks_before := days_before %% 7]
dates_to_keep <- dates_to_keep[weeks_before == 0]
dates_to_keep[, c("days_before", "weeks_before") := NULL]

graph_data2 <- graph_data2[dates_to_keep, on = .(scrape_date), nomatch = 0L]

# Remove negative sign for aesthetics
graph_data2[, cr_incr := -cr_incr]

ggplot(graph_data2, aes(x = scrape_date, y = date, colour = factor(cr_incr))) +
  geom_point() + geom_line() +
  labs(title = "Implied date of fully priced in cash rate cuts",
     x = "Data scrape date", y = NULL,
     colour = "Cut number") +
  scale_x_date(date_labels = "%b %y", date_breaks = "2 months", date_minor_breaks = "1 month") +
  scale_y_date(date_labels = "%b %y", date_breaks = "1 months", minor_breaks = NULL, sec.axis = dup_axis()) +
  scale_colour_viridis_d() +
  theme_bw() +
  theme(legend.position = "inside", legend.position.inside = c(0.15, 0.85)) +
  guides(colour = guide_legend(nrow = 2, byrow = TRUE))

```


```{r graph-total-cuts, echo=FALSE, dev='svg', warning=FALSE}

graph_data <- copy(all_data)
graph_data <- graph_data[!is.na(cash_rate)]

# Get projected cash rates
graph_data <- 
  graph_data[, .(rate_end = cash_rate[date == max(date)],
                 rate_6m = cash_rate[date == floor_date(scrape_date, "month") %m+% months(6)],
                 rate_1y = cash_rate[date == floor_date(scrape_date, "month") %m+% years(1)]
                 ),
             by = scrape_date]

# Get OCR on the scrape date
graph_data[ocr_ts, on = .(scrape_date >= date), cash_rate := value]

# Calculate the change as the diff between the lookahead rate and the OCR on the day
graph_data[, let(rate_end = rate_end - cash_rate,
                 rate_6m = rate_6m - cash_rate,
                 rate_1y = rate_1y - cash_rate)]

graph_data <- melt(graph_data, measure.vars = c("rate_end", "rate_6m", "rate_1y"))
graph_data[, variable := ordered(variable, 
                                c("rate_6m", "rate_1y", "rate_end"), 
                                c("6 months", "1 year", "End period"))]

# Show past year only
graph_data <- graph_data[scrape_date > Sys.Date() %m-% years(1)]

# labels only
label_data <- graph_data[scrape_date == max(scrape_date)]

# extend the x-axis
expand_date_axis <- function(limits) {
  # Ensure that the input limits are Date objects.
  lower <- as.Date(limits[1])
  upper <- as.Date(limits[2])
  c(lower, upper %m+% months(3))
}

latest_date <- max(graph_data$scrape_date)

ggplot(graph_data, aes(x = scrape_date, y = value, colour = variable)) +
  geom_hline(yintercept = 0, colour = "black", linewidth = 0.5, linetype = "solid") +
  geom_line() +
  geom_point(data = graph_data[scrape_date == max(scrape_date)],
             size = 2) +
  geom_text_repel(data = label_data, aes(label = paste0(variable, ": ", round(value, 2), "%")),
                  nudge_x = 7, segment.colour = NA, hjust = 0,
                  xlim = c(latest_date, NA)) +
  labs(title = "Implied cash rate cuts by period ahead",
       x = "Data scrape date", y = "Change in cash rate (ppt)") +
  scale_x_date(date_labels = "%b %Y", date_breaks = "3 months", date_minor_breaks = "1 month", limits = expand_date_axis) +
  scale_y_continuous(
    breaks = function(x) seq(rounder(range(x)[1], 0.25), rounder(range(x)[2], 0.25), by = 0.25),
    sec.axis = sec_axis(trans = ~ . / -0.25, name = "Number of 0.25ppt cuts")
    ) +
  scale_colour_viridis_d() +
  theme_bw() + 
  theme(legend.position = "none") 

```