on:
  schedule:
    - cron:  '0 14 * * *'


  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Refresh-Data

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew install xquartz --cask

      - name: Install packages
        run: Rscript -e 'install.packages(c("stringr", "tesseract", "magick", "data.table", "ggplot2", "rmarkdown"))'

      - name: Run script
        run: Rscript -e 'source("R/job.R", echo = TRUE)'
        
      - name: Update README.md
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'

      - name: Commit
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"    
